### ISSUE TITLE
Make sure gillespie returns to previous integrator setting

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#12]

**Comment by matthiaskoenig** [comment]
The call to `r.gillespie()` is now resetting the old integrator.

```
%matplotlib inline
from __future__ import print_function
import tellurium as te
r = te.loada("""
    model test
    J0: S1 -> S2; k1*S1;
    S1=100; S2=0.0; k1=0.1;
    end
""")
print(r.integrator)
s = r.gillespie()
r.plot(s)
print(r.integrator)
```

```
< roadrunner.Integrator() >
  name: cvode
  settings:
      relative_tolerance: 0.00001
      absolute_tolerance: 0.0000000001
                   stiff: true
       maximum_bdf_order: 5
     maximum_adams_order: 12
       maximum_num_steps: 20000
       maximum_time_step: 0
       minimum_time_step: 0
       initial_time_step: 0
          multiple_steps: false
      variable_step_size: false

< roadrunner.Integrator() >
  name: cvode
  settings:
      relative_tolerance: 0.00001
      absolute_tolerance: 0.0000000001
                   stiff: true
       maximum_bdf_order: 5
     maximum_adams_order: 12
       maximum_num_steps: 20000
       maximum_time_step: 0
       minimum_time_step: 0
       initial_time_step: 0
          multiple_steps: false
      variable_step_size: false
```
